{% set name = "pyfolio" %}
{% set version = "0.9.0" %}
{% set sha256 = "a296eea79c86ba5910549f3a6fcfb28e69e54c2d1b90952a7dde636b0922e745" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython >=3.2.3
    - matplotlib >=1.4.0
    - numpy >=1.9.1
    - pandas >=0.19.0
    - pytz >=2014.10
    - scipy >=0.14.0
    - scikit-learn >=0.18.2
    - seaborn >=0.7.1
    - pandas-datareader >=0.2
    - empyrical >=0.3.2
    - pymc3 >=3.1

test:
  imports:
    - pyfolio
    - pyfolio.tests

about:
  home: https://quantopian.github.io/pyfolio/
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'pyfolio is a Python library for performance and risk analysis of financial portfolios'

  description: |
    pyfolio is a Python library for performance and risk analysis
    of financial portfolios developed by Quantopian Inc. 
    It works well with the Zipline open source backtesting library.

    At the core of pyfolio is a so-called tear sheet that consists of
    various individual plots that provide a comprehensive image of the
    performance of a trading algorithm.
  doc_url: https://quantopian.github.io/pyfolio/
  dev_url: https://github.com/quantopian/pyfolio

extra:
  recipe-maintainers:
    - alen12345
