travis:
  secure:
    BINSTAR_TOKEN: iBcFBdoGCF6M3QYrPBaVzz1ezeTcB9acM0rjNbE2L24lFfovcXIICUssDwakNGJXRWser6qLYdMd9XToMTorJ8OL9+MUIlnLlgsumX9Lm49Dpqw8FqVhYXt+FSpNcgBOZt79K6XnKXVWcPPDmya67SpO5UF1wbpjA9gXMsAHmLXCbU3hNhYKE63HWzcicw0zL/2yv15Eb61untOCmEGLpdXfKyCj1IzQmp6RGJb7luXwHAX0OVPODO6cU4/NTE3g6OUlqZaU6nJm0pnnIp2ZDbQB9sO2NZq/W2dq857n4w+8RtTpDDmxAUJa0wBv/4zR41PP0+uLR43KnkC0uJppjFB7zzBaq0t72CburUM/E5FOIKVM8FTuXjdN8VNfI1mW5V2PbwWo2HVYHA6EyG2df8+DqgvPkk1nkbmWTOkScAUuxMV5jkBOUM9PHjRgukY4iIVl7jcqzR8ctwfR+/95+YOc2g+Vv3nX0fzoMwMEWZrN60QsrYLcjBxZhb2EcpNc2B/+sXjRPJVt9oUZ3rnNgI6XXwz0D2y/7k2Foli15v6GcXv+VjYyCsNLUA0J2nZUERAPj42McGdxC9Rk/ZGqy+Fu1p2IFvIpP7xVxE5lnLZDYirnlK7iCDtRZO459OZKn2NRmpszriD/26BTnrk3e9U8krS1X7GmAi9XVjikd5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
